USE [AddressBook]
GO

INSERT INTO [AddressBook].[dbo].[Country](Name, Code)
VALUES('Canada','CA'), ('USA','US')

INSERT INTO [AddressBook].[dbo].[ProvinceState](Name, Code, CountryId)
VALUES('Alabama, US','AL', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Alaska, US','AK', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Arizona, US','AZ', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Arkansas, US','AR', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Armed Forces America','AA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Armed Forces Europe','AE', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Armed Forces Pacific','AP', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('California, US','CA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Colorado, US','CO', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Connecticut, US','CT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Delaware, US','DE', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('District of Columbia, US','DC', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Florida, US','FL', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Georgia, US','GA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Hawaii, US','HI', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Idaho, US','ID', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Illinois, US','IL', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
   	  ('Indiana, US','IN', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Iowa, US','IA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
   	  ('Kansas, US','KS', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Kentucky, US','KY', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
	  ('Louisiana, US','LA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Maine, US','ME', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Maryland, US','MD', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Massachusetts, US','MA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Michigan, US','MI', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Minnesota, US','MN', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Mississippi, US','MS', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Missouri, US','MO', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Montana, US','MT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Nebraska, US','NE', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Nevada, US','NV', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('New Hampshire, US','NH', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('New Jersey, US','NJ', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('New Mexico, US','NM', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('New York, US','NY', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('North Carolina, US','NC', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')), 
      ('North Dakota, US','ND', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Ohio, US','OH', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Oklahoma, US','OK', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Oregon, US','OR', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Pennsylvania, US','PA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Rhode Island, US','RI', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('South Carolina, US','SC', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('South Dakota, US','SD', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Tennessee, US','TN', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Texas, US','TX', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Utah, US','UT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Vermont, US','VT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Virginia, US','VA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Washington, US','WA', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('West Virginia, US','WV', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Wisconsin, US','WI', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Wyoming, US','WY', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'US')),
      ('Alberta, CA','AB', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('British Columbia, CA','BC', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Manitoba, CA','MB', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('New Brunswick, CA','NB', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Newfoundland and Labrador, CA','NL', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Northwest Territories, CA','NT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Nova Scotia, CA','NS', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Nunavut, CA','NU', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Ontario, CA','ON', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Prince Edward Island, CA','PE', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Quebec, CA','QC', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Saskatchewan, CA','SK', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA')),
      ('Yukon, CA','YT', (SELECT Id from [AddressBook].[dbo].[Country] where Code = 'CA'));